api_platform:
  defaults:
    pagination_enabled: false
  mapping:
    paths:
      - "%kernel.project_dir%/src/Entity"
  formats:
    json:
      mime_types:
        - application/json
    json-ld:
      mime_types:
        - application/ld+json
    html:
      mime_types:
        - text/html
  swagger:
    api_keys:
      apiKey:
        name: Authorization
        type: header
