drenso_shared:
  public_services: false # Set whether all services must be public
  form_extensions:
    generic: false
    button: false
    select2: false
  api:
    convert_entity_validation_exception:
      enabled: true
      controller_prefix: App\Api\Controller
      data_field: violations
  database:
    softdeletable:
      enabled: true
      use_gedmo_workaround:
        enabled: false
  serializer:
    handlers:
      id_map: ~
