fm_elfinder:
  instances:
    default:
      editor: custom
      editor_template: elfinder/elfinder.html.twig
      relative_path: true
      connector:
        roots:
          uploads:
            driver: LocalFileSystem
            path: '%kernel.project_dir%/uploads'
            alias: root
            upload_allow: [ 'all' ]
            upload_max_size: 10M
