# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
  form_themes:
    - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

parameters:
  ckeditor_tags: "<p><br><span><h1><h2><h3><h4><a>
  <img><figure><figcaption>
  <ul><ol><li>
  <strong><b><em><u><s><sup><sub><pre>
  <table><tbody><thead><tr><td><th><caption>
  <ltb-abbr><div><symbol>"

fos_ck_editor:
  base_path: build/ckeditor
  js_path: build/ckeditor/ckeditor.js
  autoload: false
  jquery: true
  default_config: ltb_config
  configs:
    ltb_config: &ckeditor_default
      language: "en"
      toolbar: "ltb_toolbar"
      filebrowserBrowseRoute: "elfinder"
      filebrowserWindowWidth: "40%"
      filebrowserWindowHeight: "40%"
      format_tags: "p;h1;h2;citation;reference"
      extraPlugins: "image2,wordcount,latexeditor"
      extraAllowedContent: "span(latex-figure,latex-figure-inline);figure(latex-figure);figcaption(latex-caption);img(latex-image);a[data-concept-id](concept-link);ltb-abbr[data-abbr-id];symbol"
      removePlugins: "image,dialogadvtab"
      removeButtons: "Underline"
      bodyClass: "ltb-text-container"
      wordcount:
        showParagraphs: false
    ltb_no_image:
      <<: *ckeditor_default
      filebrowserBrowseRoute: null
    ltb_concept_config:
      <<: *ckeditor_default
      extraPlugins: "image2,wordcount,latexeditor,abbreviationselector,conceptselector,ltbbuttons"
    ltb_help:
      <<: *ckeditor_default
      extraPlugins: "image2,wordcount,ltbbuttons"
      filebrowserBrowseRouteParameters:
        studyAreaId: 0
  toolbars:
    configs:
      ltb_toolbar: [ "@text_tools", "@ltb_tools", "/", "@font_tools", "@edit_tools" ]
    items:
      edit_tools: [ "Cut", "Copy", "Paste", "PasteText", "PasteFromWord", "-", "RemoveFormat" ]
      text_tools: [ "Highlight", "Symbol", "Subscript", "Superscript", "-", "NumberedList", "BulletedList", "-", "Table" ]
      ltb_tools:  [ "Link", "Image", "LatexEditor", "ConceptSelector", "AbbreviationSelector" ]
      font_tools: [ "Format", "TextColor" ]
  plugins:
    abbreviationselector:
      path:     "/ckeditor-plugins/abbreviationselector/"
      filename: "plugin.js"
    conceptselector:
      path:     "/ckeditor-plugins/conceptselector/"
      filename: "plugin.js"
    image2:
      path:     "/ckeditor-plugins/image2/"
      filename: "plugin.js"
    latexeditor:
      path:     "/ckeditor-plugins/latexeditor/"
      filename: "plugin.js"
    ltbbuttons:
      path:     "/ckeditor-plugins/ltbbuttons/"
      filename: "plugin.js"
    wordcount:
      path:     "/ckeditor-plugins/wordcount/"
      filename: "plugin.js"
