twig:
  default_path: '%kernel.project_dir%/templates'
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  file_name_pattern: '*.twig'
  form_themes:
    - "_form/form_layout.html.twig"
    - "_form/_button_layout.html.twig"
    - "_form/_collection_layout.html.twig"
    - "_form/_download_preview_layout.html.twig"
    - "_form/_learning_paths_layout.html.twig"
    - "_form/_custom_types_layout.html.twig"
    - "_form/_review_layout.html.twig"
  paths:
    '%kernel.project_dir%/assets/email/img': email_img
    '%kernel.project_dir%/public/email': email_assets
  globals:
    allowed_ckeditor_tags: '%ckeditor_tags%'
    naming: '@App\Naming\NamingService'
    sentry_dsn: '%env(SENTRY_JS_DSN)%'
    sentry_release: '%sentry_release%'

when@test:
  twig:
    strict_variables: true
