version: '3.4'

services:
  ltb:
    build:
      context: .
      target: ltb_dev
      dockerfile: docker/ltb/Dockerfile
    restart: always
    volumes:
      - './:/usr/src/app/'
    environment:
      APP_ENV: dev
      PYTHON_PATH: '/usr/local/bin/python3.8'
      DATABASE_CHECK: 'db:3306'
      DATABASE_URL: 'mysql://ltb:%database_password%@db:3306/ltb'
      PRODUCTION_SERVER: 'false'
      TRUSTED_PROXIES: 10.9.8.1
      HTTP_HOST: localhost
    depends_on:
      - db
    networks:
      - ltb-network

  nginx:
    image: nginx:1.25.1-alpine
    restart: always
    volumes:
      - './:/usr/src/app:ro'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
      - './docker/nginx/server.cert:/etc/nginx/certs/server.cert:ro'
      - './docker/nginx/server.key:/etc/nginx/certs/server.key:ro'
    depends_on:
      - ltb
    ports:
      - '10443:443'
    networks:
      - ltb-network

  db:
    image: mariadb:10.11.4
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    restart: always
    environment:
      MYSQL_USER: ltb
      MYSQL_DATABASE: ltb
    env_file:
      - docker/db.env
    volumes:
      - 'ltb-database:/var/lib/mysql'
    ports:
      - '13306:3306'
    networks:
      - ltb-network

volumes:
  ltb-database:
  ltb-uploads:
  ltb-public:

networks:
  ltb-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.9.8.0/24
