#! /bin/bash -e

# Put the website on updating
cp update/controllers/update.php public/index.php

# Pull the new data
ssh-agent bash -c 'ssh-add /home/x1002348/.ssh/gitlab-deploy; git pull'

# Install/update composer for usage
./install-composer.sh

# Install vendors / clear cache
COMPOSER_CACHE_DIR=/tmp/composer; php composer.phar install -o --apcu-autoloader --no-dev

# Execute migrations
sudo -u www-data php bin/console doctrine:migrations:migrate -n

# Clear cache
sudo -u www-data php bin/console cache:clear
